/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.view;

import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.util.ArrayList;

/**
 *
 * @author seabirds
 */
public class NavieTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form NavieTestFrame
     */
    NavieBayes1 nb;
    String dSet[][];

    String colName[];
    String colType[];
    int concnt = 0;
    ArrayList clsProb = new ArrayList();
    double nData[][];

    public NavieTestFrame(NavieBayes1 n) {
        initComponents();
        nb = n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTestDataPath = new javax.swing.JTextField();
        btnTestset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnClassify2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intrusion Detection System To Detect Ddos Attack In Gnutella Hybrid P2p Network ");
        setFocusableWindowState(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Intrusion Detection System To Detect Ddos Attack In Gnutella Hybrid P2p Network ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jLabel2.setText("Test Data Set");

        txtTestDataPath.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        txtTestDataPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestDataPathActionPerformed(evt);
            }
        });

        btnTestset.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        btnTestset.setText("....");
        btnTestset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestsetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(txtTestDataPath, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnTestset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnTestset)
                    .addComponent(txtTestDataPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.NO", "Protocol Type", "Service", "Flag"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnClassify2.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        btnClassify2.setText("Classify");
        btnClassify2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassify2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(btnClassify2)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClassify2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassify2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassify2ActionPerformed
        // TODO add your handling code here:
        try {
            readData();
            clsProb();
            computePosterior();
            dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnClassify2ActionPerformed

    public void readData() {
        try {
            File fe = new File(txtTestDataPath.getText().trim());
            FileInputStream fis = new FileInputStream(fe);
            byte data[] = new byte[fis.available()];
            fis.read(data);
            fis.close();

            String sg1[] = new String(data).split("\n");
            String col[] = sg1[0].split("\t");
            String colty[] = sg1[1].split("\t");
            colName = new String[col.length];
            colType = new String[col.length];

            for (int i = 0; i < col.length; i++) {
                colName[i] = col[i];
                colType[i] = colty[i];
                if (colty[i].trim().equals("con")) {
                    concnt++;
                }
            }

            dSet = new String[sg1.length - 2][col.length];

            for (int i = 2; i < sg1.length; i++) {
                String sg2[] = sg1[i].split("\t");
                for (int j = 0; j < sg2.length; j++) {
                    dSet[i - 2][j] = sg2[j];
                }

            }

            nData = new double[dSet.length][concnt];
            int cc1 = 0;
            for (int i = 0; i < colType.length; i++) {
                if (colType[i].trim().equals("con")) {
                    for (int j = 0; j < dSet.length; j++) {
                        nData[j][cc1] = Double.parseDouble(dSet[j][i]);
                    }
                    cc1++;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clsProb() {
        for (int i = 0; i < nb.cls.size(); i++) {
            int kk = Integer.parseInt(nb.clsCnt.get(i).toString());
            double prob1 = (double) kk / (double) nb.dSet.length;
            clsProb.add(prob1);
        }
        System.out.println("cls Prob" + clsProb);
        System.out.println(concnt + " : " + nb.means.size());

    }

    public void computePosterior() {
        ResultFrame rf = new ResultFrame();
        DefaultTableModel dm1 = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel dm2 = (DefaultTableModel) rf.jTable1.getModel();
        rf.setVisible(true);
//        rf.setTitle("Result - Navibayes");
        rf.setResizable(false);

        ArrayList at2 = new ArrayList();
        for (int ii = 0; ii < nData.length; ii++) {
            double evd = 0;
            ArrayList at1 = new ArrayList();
            for (int i = 0; i < nb.cls.size(); i++) {
                double d1 = Double.parseDouble(clsProb.get(i).toString());
                //System.out.println(nb.cls.get(i).toString());
                for (int j = 0; j < nb.means.size(); j++) {
                    String g1[] = nb.means.get(j).toString().split("@");
                    String mns1[] = g1[i].split("#");
                    double mn = Double.parseDouble(mns1[0]);
                    double std = Double.parseDouble(mns1[1]);

                    double e1 = 1.0 / Math.sqrt(2.0 * Math.PI * (std * std));
                    double e2 = Math.exp((-(nData[ii][j] - mn) * (nData[ii][j] - mn)) / (2.0 * (std * std)));

                    if (String.valueOf(e1).equals("Infinity") || String.valueOf(e1).equals("NaN")) {
                        e1 = 1;
                    }
                    if (String.valueOf(e2).equals("Infinity") || String.valueOf(e2).equals("NaN")) {
                        e2 = 1;
                    }

                    double e3 = e1 * e2;
                    if (String.valueOf(e3).equals("Infinity")) {
                        e3 = 1;
                    }
                    //System.out.println("\t "+e3 +" : "+e1+" : "+e2);
                    d1 = d1 * e3;

                }
                at1.add(d1);
                evd = evd + d1;
            }

            //System.out.println("evd "+evd);
            // System.out.println("post  "+at1);
            double max = Double.parseDouble(at1.get(0).toString());
            for (int i = 1; i < at1.size(); i++) {
                max = Math.max(max, Double.parseDouble(at1.get(i).toString()));
            }
            //System.out.println("max "+max);
            int ind = at1.indexOf(max);
            String r1 = nb.cls.get(ind).toString();
            System.out.println("--> " + ii + " : " + r1);
            Vector v1 = new Vector();
            v1.add(dm1.getValueAt(ii, 0));
            v1.add(dm1.getValueAt(ii, 1));
            v1.add(dm1.getValueAt(ii, 2));
            v1.add(dm1.getValueAt(ii, 3));
            v1.add(r1);
            dm2.addRow(v1);
        }

    }


    private void btnTestsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestsetActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser(".");
            int ch = fc.showOpenDialog(this);
            if (ch == JFileChooser.APPROVE_OPTION) {
                String path = fc.getSelectedFile().getAbsolutePath();
                txtTestDataPath.setText(path);

                File fe = new File(path);
                FileInputStream fis = new FileInputStream(fe);
                byte data[] = new byte[fis.available()];
                fis.read(data);
                fis.close();

                DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
                String sg1[] = new String(data).split("\n");
                for (int i = 2; i < sg1.length; i++) {
                    String sg2[] = sg1[i].split("\t");
                    Vector v = new Vector();
                    v.add(i - 1);
                    v.add(sg2[1]);
                    v.add(sg2[2]);
                    v.add(sg2[3]);
                    //v.add(sg2[41]);
                    dm.addRow(v);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTestsetActionPerformed

    private void txtTestDataPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestDataPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestDataPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavieTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavieTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavieTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavieTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NavieTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassify2;
    private javax.swing.JButton btnTestset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTestDataPath;
    // End of variables declaration//GEN-END:variables
}
